### ISSUE TITLE
limit of 3 edits per day is not removed

### ISSUE THREAD

**Issue by Rainson12** [gookie-dev/sejda-crack#1]
luckily this solution doesnt work :)

**Comment by gookie-dev** [comment]
fixed [commit 424f70e](https://github.com/gookie-dev/sejda-crack/commit/424f70ed1296a9fcc6f32ca3f1b080468a8f1c6d)

**Comment by Blaz3Mar1n** [comment]
> fixed [commit 424f70e](https://github.com/gookie-dev/sejda-crack/commit/424f70ed1296a9fcc6f32ca3f1b080468a8f1c6d)

Thank you so much
