### ISSUE TITLE
Not able to find path to Sejda PDF Desktop preferences:

### ISSUE THREAD

**Issue by reactivicky** [gookie-dev/sejda-crack#3]
![Screenshot from 2024-08-23 16-00-51](https://github.com/user-attachments/assets/824c7c4b-1cf0-4a5c-a312-a4ba22aff52f)

**Comment by reactivicky** [comment]
Ok you have to open sejda desktop first so that it will create a directory in the default location. And then after closing sejda desktop, you have to run the python script. Thanks
Please update readme

**Comment by Johnito974** [comment]
I've opened the software already and closed it, but that didn't solve the issue :(
