### ISSUE TITLE
Password required

### ISSUE THREAD

**Issue by Johnito974** [gookie-dev/sejda-crack#4]
Hello, when i do the command on my Mac they ask me for a password, do you know what should i put please? Thank you!
<img width="405" alt="image" src="https://github.com/user-attachments/assets/0e26d81f-780f-4535-8da6-c6036a9ca617">

**Comment by gookie-dev** [comment]
well, your acc / login password

**Comment by Johnito974** [comment]
It doesn't work :( and it's like it's not writting anything when im typing

**Comment by gookie-dev** [comment]
bruh, your first time using bash?
its called password masking. you cant see it, but it types actually.

**Comment by Johnito974** [comment]
Yes but that doesnt zork thats why i thought its not writting anything :( Should i write only the password?

**Comment by Johnito974** [comment]
I'm sorry it's my first time

**Comment by Johnito974** [comment]
Ah it worked! but i ahve another message 'no such file or directory'

**Comment by gookie-dev** [comment]
https://support.apple.com/guide/terminal/enter-administrator-commands-apd5b0b6259-a7d4-4435-947d-0dff528912ba/mac

**Comment by gookie-dev** [comment]
https://github.com/gookie-dev/sejda-crack/issues/3#issuecomment-2306804966

**Comment by gookie-dev** [comment]
You probably missed this:
> Navigate to the directory containing the sejda-crack.py script.

Use `cd Download` or wherever you downloaded the `sejda-crack.py`.

**Comment by Johnito974** [comment]
I don't think i forgot it 
<img width="469" alt="image" src="https://github.com/user-attachments/assets/6437e623-9f05-419a-9878-30470782a0c1">

**Comment by gookie-dev** [comment]
https://youtu.be/ZdaJnCFJU70?feature=shared
